# Prepare the dataset with the full set of features to use in Feature Selection process.
Difference: less strict outliers detection.

Save the resulting dataset for Feature Selection process: RICKD_FEATURE_SELECTION_DATA_FILE_2

In [1]:
import core.constants as c

from core.matlab_data_loader import MatlabDataLoader
from core.markers import visualize_marker_trajectories
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas.api.types import is_numeric_dtype

In [2]:
loader = MatlabDataLoader()

full_data = loader.get_discrete_with_metadata()
display(full_data)

,ID,Speed_Output,Label,Hz,Step_Width_Left,Step_Width_Right,Stride_Rate_Left,Stride_Rate_Right,Stride_Length_Left,Stride_Length_Right,...,injury_desc,injury2_desc,injury_name,injury2_name,injured_joint_code,injured_joint2_code,injured_side_code,injured_side2_code,has_no_injury,is_injured
0,100001_20110531T161051,2.489233,run,200,0.123419,0.123419,78.947368,78.947368,1.891817,1.891817,...,Inflammation or irritation of Achilles tendon ...,No injury has been diagnosed.,achilles tendonitis,no injury,ankle,no_injury,left,right,False,True
1,100002_20110601T140505,2.722687,run,200,0.032922,0.032922,81.632653,81.632653,2.001175,2.001175,...,Painful friction of iliotibial band rubbing ov...,No injury has been diagnosed.,itb syndrome,no injury,thigh,no_injury,right,right,False,True
2,100003_20110601T095930,2.949904,run,200,0.097273,0.097273,78.947368,78.947368,2.241927,2.241927,...,Pain around kneecap caused by poor tracking an...,General sensation of discomfort without speci...,patellofemoral pain syndrome,pain,knee,foot,left,left,False,True
3,100004_20110203T120721,2.688014,run,200,0.011401,0.011401,82.191781,82.191781,1.962250,1.962250,...,Overstretching or tearing of the calf muscle f...,No injury has been diagnosed.,calf muscle strain,no injury,lower_leg,no_injury,right,right,False,True
4,100004_20140929T102035,2.928598,run,200,0.029021,0.029021,83.333333,82.758621,2.108590,2.123233,...,No injury has been diagnosed.,No injury has been diagnosed.,no injury,no injury,no_injury,no_injury,no_injury,no_injury,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1808,201100_20150409T155915,2.790966,run,200,0.108809,0.108809,76.433121,76.433121,2.190908,2.190908,...,Muscle fibers stretched or torn due to excessi...,Stretching or tearing of ligaments due to exce...,muscle strain,ligament sprain,lumbar_spine,ankle,bilateral,right,False,True
1809,201101_20150413T143152,2.828602,run,200,0.090986,0.090986,88.235294,88.235294,1.923449,1.923449,...,No injury has been diagnosed.,No injury has been diagnosed.,no injury,no injury,no_injury,no_injury,no_injury,no_injury,True,False
1810,201223_20140415T132359,2.876889,run,200,0.157843,0.157843,80.000000,80.536913,2.157667,2.143282,...,No injury has been diagnosed.,No injury has been diagnosed.,no injury,no injury,no_injury,no_injury,no_injury,no_injury,True,False
1811,201224_20140417T141711,2.921736,run,200,0.071881,0.071881,78.431373,78.947368,2.235128,2.220519,...,Painful friction of iliotibial band rubbing ov...,No injury has been diagnosed.,itb syndrome,no injury,thigh,no_injury,left,no_injury,False,True
1812,201225_20140515T133244,2.904997,run,200,0.057887,0.057887,92.307692,91.955373,1.888248,1.895511,...,General sensation of discomfort without speci...,No injury has been diagnosed.,pain,no injury,foot,no_injury,left,no_injury,False,True

Columns from both datasets can be considered equal. The difference is only in the case of the speed, which is equalto 4 decimal places. When studying human running speed, this is negligible.

## Columns Selection

NOTES:
- We have removed columns that are not useful for our analysis, like the years running, file path, activities, ...
- We have also removed duplicate values like speed_r.
- When information is present in both discrete variables file and metadata file, we have taken the discrete variables file as we have been the ones that have computed the values.
- We have removed columns that have been merged into is_injured (injury_code, injury_severity, injured_side, etc..).

### Columns to Keep:

| #   | Column                          | Dtype    |
|-----|---------------------------------|----------|
| 0   | ID                              | object   |
| 1   | Speed_Output                    | float64  |
| 3   | Hz                              | int64    |
| 4   | Step_Width_Left                 | float64  |
| 5   | Step_Width_Right                | float64  |
| 6   | Stride_Rate_Left                | float64  |
| 7   | Stride_Rate_Right               | float64  |
| 8   | Stride_Length_Left              | float64  |
| 9   | Stride_Length_Right             | float64  |
| 10  | Swing_Time_Left                 | float64  |
| 11  | Swing_Time_Right                | float64  |
| 12  | Stance_Time_Left                | float64  |
| 13  | Stance_Time_Right               | float64  |
| 14  | Pelvis_Peak_Drop_Angle_Left     | float64  |
| 15  | Pelvis_Peak_Drop_Angle_Right    | float64  |
| 16  | Pelvis_Drop_Excursion_Left      | float64  |
| 17  | Pelvis_Drop_Excursion_Right     | float64  |
| 18  | Ankle_DF_Peak_Angle_Left        | float64  |
| 19  | Ankle_DF_Peak_Angle_Right       | float64  |
| 20  | Ankle_Eve_Peak_Angle_Left       | float64  |
| 21  | Ankle_Eve_Peak_Angle_Right      | float64  |
| 22  | Ankle_Eve_Percent_Stance_Left   | float64  |
| 23  | Ankle_Eve_Percent_Stance_Right  | float64  |
| 24  | Ankle_Eve_Excursion_Left        | float64  |
| 25  | Ankle_Eve_Excursion_Right       | float64  |
| 26  | Ankle_Rot_Peak_Angle_Left       | float64  |
| 27  | Ankle_Rot_Peak_Angle_Right      | float64  |
| 28  | Ankle_Rot_Excursion_Left        | float64  |
| 29  | Ankle_Rot_Excursion_Right       | float64  |
| 30  | Knee_Flex_Peak_Angle_Left       | float64  |
| 31  | Knee_Flex_Peak_Angle_Right      | float64  |
| 32  | Knee_Add_Peak_Angle_Left        | float64  |
| 33  | Knee_Add_Peak_Angle_Right       | float64  |
| 34  | Knee_Add_Excursion_Left         | float64  |
| 35  | Knee_Add_Excursion_Right        | float64  |
| 36  | Knee_Abd_Peak_Angle_Left        | float64  |
| 37  | Knee_Abd_Peak_Angle_Right       | float64  |
| 38  | Knee_Abd_Excursion_Left         | float64  |
| 39  | Knee_Abd_Excursion_Right        | float64  |
| 40  | Knee_Rot_Peak_Angle_Left        | float64  |
| 41  | Knee_Rot_Peak_Angle_Right       | float64  |
| 42  | Knee_Rot_Excursion_Left         | float64  |
| 43  | Knee_Rot_Excursion_Right        | float64  |
| 44  | Hip_Ext_Peak_Angle_Left         | float64  |
| 45  | Hip_Ext_Peak_Angle_Right        | float64  |
| 46  | Hip_Add_Peak_Angle_Left         | float64  |
| 47  | Hip_Add_Peak_Angle_Right        | float64  |
| 48  | Hip_Add_Excursion_Left          | float64  |
| 49  | Hip_Add_Excursion_Right         | float64  |
| 50  | Hip_Rot_Peak_Angle_Left         | float64  |
| 51  | Hip_Rot_Peak_Angle_Right        | float64  |
| 52  | Hip_Rot_Excursion_Left          | float64  |
| 53  | Hip_Rot_Excursion_Right         | float64  |
| 54  | Foot_Prog_Angle_Left            | float64  |
| 55  | Foot_Prog_Angle_Right           | float64  |
| 56  | Foot_Ang_At_HS_Left             | float64  |
| 57  | Foot_Ang_At_HS_Right            | float64  |
| 58  | MHW_Exc_From_TO_Left            | float64  |
| 59  | MHW_Exc_From_TO_Right           | float64  |
| 60  | Ankle_Eve_Peak_Vel_Left         | float64  |
| 61  | Ankle_Eve_Peak_Vel_Right        | float64  |
| 62  | Ankle_Rot_Peak_Vel_Left         | float64  |
| 63  | Ankle_Rot_Peak_Vel_Right        | float64  |
| 64  | Knee_Abd_Peak_Vel_Left          | float64  |
| 65  | Knee_Abd_Peak_Vel_Right         | float64  |
| 66  | Knee_Add_Peak_Vel_Left          | float64  |
| 67  | Knee_Add_Peak_Vel_Right         | float64  |
| 68  | Hip_Abd_Peak_Vel_Left           | float64  |
| 69  | Hip_Abd_Peak_Vel_Right          | float64  |
| 70  | Knee_Rot_Peak_Vel_Left          | float64  |
| 71  | Knee_Rot_Peak_Vel_Right         | float64  |
| 72  | Hip_Rot_Peak_Vel_Left           | float64  |
| 73  | Hip_Rot_Peak_Vel_Right          | float64  |
| 74  | Pronation_Onset_Left            | int64    |
| 75  | Pronation_Onset_Right           | int64    |
| 76  | Supination_Timing_Left          | int64    |
| 77  | Supination_Timing_Right         | int64    |
| 78  | Hip_Add_Peak_Vel_Left           | float64  |
| 79  | Hip_Add_Peak_Vel_Right          | float64  |
| 80  | Pelvic_Drop_Peak_Vel_Left       | float64  |
| 81  | Pelvic_Drop_Peak_Vel_Right      | float64  |
| 82  | Vertical_Oscillation_Left       | float64  |
| 83  | Vertical_Oscillation_Right      | float64  |
| 89  | age                             | float64  |
| 90  | Height                          | float64  |
| 91  | Weight                          | float64  |
| 92  | Gender                          | object   |
| 93  | DominantLeg                     | object   |
| 197 | is_injured                      | bool     |

In [3]:
cols_to_keep = [
    "ID",
    "Speed_Output",
    "Step_Width_Left",
    "Step_Width_Right",
    "Stride_Rate_Left",
    "Stride_Rate_Right",
    "Stride_Length_Left",
    "Stride_Length_Right",
    "Swing_Time_Left",
    "Swing_Time_Right",
    "Stance_Time_Left",
    "Stance_Time_Right",
    "Pelvis_Peak_Drop_Angle_Left",
    "Pelvis_Peak_Drop_Angle_Right",
    "Pelvis_Drop_Excursion_Left",
    "Pelvis_Drop_Excursion_Right",
    "Ankle_DF_Peak_Angle_Left",
    "Ankle_DF_Peak_Angle_Right",
    "Ankle_Eve_Peak_Angle_Left",
    "Ankle_Eve_Peak_Angle_Right",
    "Ankle_Eve_Percent_Stance_Left",
    "Ankle_Eve_Percent_Stance_Right",
    "Ankle_Eve_Excursion_Left",
    "Ankle_Eve_Excursion_Right",
    "Ankle_Rot_Peak_Angle_Left",
    "Ankle_Rot_Peak_Angle_Right",
    "Ankle_Rot_Excursion_Left",
    "Ankle_Rot_Excursion_Right",
    "Knee_Flex_Peak_Angle_Left",
    "Knee_Flex_Peak_Angle_Right",
    "Knee_Add_Peak_Angle_Left",
    "Knee_Add_Peak_Angle_Right",
    "Knee_Add_Excursion_Left",
    "Knee_Add_Excursion_Right",
    "Knee_Abd_Peak_Angle_Left",
    "Knee_Abd_Peak_Angle_Right",
    "Knee_Abd_Excursion_Left",
    "Knee_Abd_Excursion_Right",
    "Knee_Rot_Peak_Angle_Left",
    "Knee_Rot_Peak_Angle_Right",
    "Knee_Rot_Excursion_Left",
    "Knee_Rot_Excursion_Right",
    "Hip_Ext_Peak_Angle_Left",
    "Hip_Ext_Peak_Angle_Right",
    "Hip_Add_Peak_Angle_Left",
    "Hip_Add_Peak_Angle_Right",
    "Hip_Add_Excursion_Left",
    "Hip_Add_Excursion_Right",
    "Hip_Rot_Peak_Angle_Left",
    "Hip_Rot_Peak_Angle_Right",
    "Hip_Rot_Excursion_Left",
    "Hip_Rot_Excursion_Right",
    "Foot_Prog_Angle_Left",
    "Foot_Prog_Angle_Right",
    "Foot_Ang_At_HS_Left",
    "Foot_Ang_At_HS_Right",
    "MHW_Exc_From_TO_Left",
    "MHW_Exc_From_TO_Right",
    "Ankle_Eve_Peak_Vel_Left",
    "Ankle_Eve_Peak_Vel_Right",
    "Ankle_Rot_Peak_Vel_Left",
    "Ankle_Rot_Peak_Vel_Right",
    "Knee_Abd_Peak_Vel_Left",
    "Knee_Abd_Peak_Vel_Right",
    "Knee_Add_Peak_Vel_Left",
    "Knee_Add_Peak_Vel_Right",
    "Hip_Abd_Peak_Vel_Left",
    "Hip_Abd_Peak_Vel_Right",
    "Knee_Rot_Peak_Vel_Left",
    "Knee_Rot_Peak_Vel_Right",
    "Hip_Rot_Peak_Vel_Left",
    "Hip_Rot_Peak_Vel_Right",
    "Pronation_Onset_Left",
    "Pronation_Onset_Right",
    "Supination_Timing_Left",
    "Supination_Timing_Right",
    "Hip_Add_Peak_Vel_Left",
    "Hip_Add_Peak_Vel_Right",
    "Pelvic_Drop_Peak_Vel_Left",
    "Pelvic_Drop_Peak_Vel_Right",
    "Vertical_Oscillation_Left",
    "Vertical_Oscillation_Right",
    "age",
    "Height",
    "Weight",
    "Gender",
    "DominantLeg",
    "is_injured"
]

# Print which columns are being dropped
dropped_columns = [col for col in full_data.columns if col not in cols_to_keep]
if dropped_columns:
    print("Dropped columns:", dropped_columns)
else:
    print("No columns were dropped.")

full_data_selected = full_data[cols_to_keep]
full_data_selected.columns = [col.lower() for col in full_data_selected.columns]

full_data_selected.head()

Dropped columns: ['Label', 'Hz', 'id', 'sub_id', 'datestring', 'filename', 'speed_r', 'Activities', 'Level', 'YrsRunning', 'RaceDistance', 'RaceTimeHrs', 'RaceTimeMins', 'RaceTimeSecs', 'YrPR', 'NumRaces', 'session_file_path', 'l_step_width', 'l_stride_rate', 'l_stride_length', 'l_swing_time', 'l_stance_time', 'l_pelvis_peak_drop_angle', 'l_pelvis_drop_excursion', 'l_ankle_df_peak_angle', 'l_ankle_eve_peak_angle', 'l_ankle_eve_percent_stance', 'l_ankle_eve_excursion', 'l_ankle_rot_peak_angle', 'l_ankle_rot_excursion', 'l_knee_flex_peak_angle', 'l_knee_add_peak_angle', 'l_knee_add_excursion', 'l_knee_abd_peak_angle', 'l_knee_abd_excursion', 'l_knee_rot_peak_angle', 'l_knee_rot_excursion', 'l_hip_ext_peak_angle', 'l_hip_add_peak_angle', 'l_hip_add_excursion', 'l_hip_rot_peak_angle', 'l_hip_rot_excursion', 'l_foot_prog_angle', 'l_foot_ang_at_hs', 'l_mhw_exc_from_to', 'l_ankle_eve_peak_vel', 'l_ankle_rot_peak_vel', 'l_knee_abd_peak_vel', 'l_knee_add_peak_vel', 'l_hip_abd_peak_vel', 'l_knee_rot_peak_vel', 'l_hip_rot_peak_vel', 'l_pronation_onset', 'l_pronation_offset', 'l_peak_hip_add_velocity', 'l_peak_pelvic_drop_velocity', 'l_vertical_oscillation', 'r_step_width', 'r_stride_rate', 'r_stride_length', 'r_swing_time', 'r_stance_time', 'r_pelvis_peak_drop_angle', 'r_pelvis_drop_excursion', 'r_ankle_df_peak_angle', 'r_ankle_eve_peak_angle', 'r_ankle_eve_percent_stance', 'r_ankle_eve_excursion', 'r_ankle_rot_peak_angle', 'r_ankle_rot_excursion', 'r_knee_flex_peak_angle', 'r_knee_add_peak_angle', 'r_knee_add_excursion', 'r_knee_abd_peak_angle', 'r_knee_abd_excursion', 'r_knee_rot_peak_angle', 'r_knee_rot_excursion', 'r_hip_ext_peak_angle', 'r_hip_add_peak_angle', 'r_hip_add_excursion', 'r_hip_rot_peak_angle', 'r_hip_rot_excursion', 'r_foot_prog_angle', 'r_foot_ang_at_hs', 'r_mhw_exc_from_to', 'r_ankle_eve_peak_vel', 'r_ankle_rot_peak_vel', 'r_knee_abd_peak_vel', 'r_knee_add_peak_vel', 'r_hip_abd_peak_vel', 'r_knee_rot_peak_vel', 'r_hip_rot_peak_vel', 'r_pronation_onset', 'r_pronation_offset', 'r_peak_hip_add_velocity', 'r_peak_pelvic_drop_velocity', 'r_vertical_oscillation', 'injury_severity_code', 'injury_severity_value', 'injury_code', 'injury2_code', 'injury_desc', 'injury2_desc', 'injury_name', 'injury2_name', 'injured_joint_code', 'injured_joint2_code', 'injured_side_code', 'injured_side2_code', 'has_no_injury']

,id,speed_output,step_width_left,step_width_right,stride_rate_left,stride_rate_right,stride_length_left,stride_length_right,swing_time_left,swing_time_right,...,pelvic_drop_peak_vel_left,pelvic_drop_peak_vel_right,vertical_oscillation_left,vertical_oscillation_right,age,height,weight,gender,dominantleg,is_injured
0,100001_20110531T161051,2.489233,0.123419,0.123419,78.947368,78.947368,1.891817,1.891817,0.4350,0.420,...,-82.090017,-57.417845,96.433793,92.586134,47.0,172.0,61.9,female,left,True
1,100002_20110601T140505,2.722687,0.032922,0.032922,81.632653,81.632653,2.001175,2.001175,0.4450,0.420,...,-57.724685,-60.462411,86.521432,94.945518,37.0,173.4,70.6,male,left,True
2,100003_20110601T095930,2.949904,0.097273,0.097273,78.947368,78.947368,2.241927,2.241927,0.4475,0.445,...,-82.171073,-95.302664,82.680986,76.611379,51.0,186.0,86.5,male,right,True
3,100004_20110203T120721,2.688014,0.011401,0.011401,82.191781,82.191781,1.962250,1.962250,0.4400,0.460,...,-63.319119,-49.646132,92.593339,83.273183,35.0,175.6,59.0,male,left,True
4,100004_20140929T102035,2.928598,0.029021,0.029021,83.333333,82.758621,2.108590,2.123233,0.4200,0.430,...,-32.717949,-52.004473,87.481400,75.091789,39.0,175.0,61.0,male,left,False

In [8]:
full_data_selected.to_csv(c.RICKD_FEATURE_SELECTION_DATA_FILE_2, index=False)